### PR TITLE
Token Grabber removed + 100% Deobfusced

### PR DESCRIPTION
**Pull request by 002-sans**
You're just a shit dev :(

### CODE REVIEW

**Comment by devrock07** [comment]
I know my son

**Comment by devrock07** [comment]
> Hes my dad

And where is grabber

**Comment by 002-sans** [comment]
index.js, your api :)

**Comment by devrock07** [comment]
> index.js, your api :)

Already patched by me check noob

**Comment by 002-sans** [comment]
2 weeks ago lol, you're just a big shit, chatgpt dev :)

**Comment by devrock07** [comment]
> 2 weeks ago lol, you're just a big shit, chatgpt dev :)

Don't change the topic skidder

**Comment by 002-sans** [comment]
MDRRRR IL A DIT "SKIDDER" lmao, shut the fuck up lil skid + chatgpt dev :)

**Pull request closed without merging**
